# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView
import sys
import io
import folium


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"    background-color: #BDBBBE;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_left = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_left.setMaximumSize(QtCore.QSize(240, 16777215))
        self.frame_left.setStyleSheet("#frame_left {\n"
"    background-color: #f9f9f9;\n"
"    border-radius: 4px;\n"
"}")
        self.frame_left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_data = QtWidgets.QFrame(parent=self.frame_left)
        self.frame_data.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_data.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_data.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_data.setObjectName("frame_data")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_data)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_data_1 = QtWidgets.QFrame(parent=self.frame_data)
        self.frame_data_1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_data_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_data_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_data_1.setObjectName("frame_data_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_data_1)
        self.horizontalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textbox_data = QtWidgets.QPlainTextEdit(parent=self.frame_data_1)
        self.textbox_data.setStyleSheet("#textbox_data {\n"
"    padding: 2px 6px;\n"
"    border-radius: 4px;\n"
"    background: transparent;\n"
"    font-size: 12px;\n"
"    border: 1px solid #BDBBBE;\n"
"}\n"
"")
        self.textbox_data.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textbox_data.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textbox_data.setObjectName("textbox_data")
        self.horizontalLayout_2.addWidget(self.textbox_data)
        self.btn_data = QtWidgets.QPushButton(parent=self.frame_data_1)
        self.btn_data.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_data.setStyleSheet("#btn_data {\n"
"    border-radius:4px;\n"
"    border: 0.5px solid #BDBBBE;\n"
"}\n"
"\n"
"#btn_data:hover{\n"
"    background-color: #D7D5D8;\n"
"}")
        self.btn_data.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/folder_open.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_data.setIcon(icon)
        self.btn_data.setIconSize(QtCore.QSize(24, 24))
        self.btn_data.setObjectName("btn_data")
        self.horizontalLayout_2.addWidget(self.btn_data)
        self.verticalLayout_2.addWidget(self.frame_data_1)
        self.frame_data_2 = QtWidgets.QFrame(parent=self.frame_data)
        self.frame_data_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_data_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_data_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_data_2.setObjectName("frame_data_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_data_2)
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textbox_vid = QtWidgets.QPlainTextEdit(parent=self.frame_data_2)
        self.textbox_vid.setStyleSheet("#textbox_vid {\n"
"    padding: 2px 6px;\n"
"    border-radius: 4px;\n"
"    background: transparent;\n"
"    font-size: 12px;\n"
"    border: 1px solid #BDBBBE;\n"
"}\n"
"")
        self.textbox_vid.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textbox_vid.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textbox_vid.setObjectName("textbox_vid")
        self.horizontalLayout_3.addWidget(self.textbox_vid)
        self.btn_vid = QtWidgets.QPushButton(parent=self.frame_data_2)
        self.btn_vid.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_vid.setStyleSheet("#btn_vid {\n"
"    border-radius:4px;\n"
"    border: 0.5px solid #BDBBBE;\n"
"}\n"
"\n"
"#btn_vid:hover{\n"
"    background-color: #D7D5D8;\n"
"}")
        self.btn_vid.setText("")
        self.btn_vid.setIcon(icon)
        self.btn_vid.setIconSize(QtCore.QSize(24, 24))
        self.btn_vid.setObjectName("btn_vid")
        self.horizontalLayout_3.addWidget(self.btn_vid)
        self.verticalLayout_2.addWidget(self.frame_data_2)
        self.frame_data_3 = QtWidgets.QFrame(parent=self.frame_data)
        self.frame_data_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_data_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_data_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_data_3.setObjectName("frame_data_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_data_3)
        self.horizontalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_submit = QtWidgets.QPushButton(parent=self.frame_data_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_submit.sizePolicy().hasHeightForWidth())
        self.btn_submit.setSizePolicy(sizePolicy)
        self.btn_submit.setStyleSheet("#btn_submit {\n"
"    padding: 6px 16px;\n"
"    border-radius: 4px;\n"
"    font-size: 12px;\n"
"    background-color: #6A676E;\n"
"    color: #f9f9f9;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#btn_submit:hover {\n"
"    background-color: #514E55;\n"
"}")
        self.btn_submit.setDefault(False)
        self.btn_submit.setFlat(False)
        self.btn_submit.setObjectName("btn_submit")
        self.horizontalLayout_4.addWidget(self.btn_submit)
        self.verticalLayout_2.addWidget(self.frame_data_3)
        self.verticalLayout.addWidget(self.frame_data)
        self.frame_list = QtWidgets.QFrame(parent=self.frame_left)
        self.frame_list.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_list.setStyleSheet("#frame_list {\n"
"    border-top: 2px solid #BDBBBE;\n"
"}")
        self.frame_list.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_list.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_list.setObjectName("frame_list")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_list)
        self.verticalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_list)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("#scrollArea {\n"
"    border: 0px;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 212, 907))
        self.scrollAreaWidgetContents.setStyleSheet("#scrollAreaWidgetContents {\n"
"    background-color: #f9f9f9;\n"
"    border: 0px;\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_data = QtWidgets.QVBoxLayout()
        self.verticalLayout_data.setObjectName("verticalLayout_data")
        self.data = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.data.setMinimumSize(QtCore.QSize(0, 60))
        self.data.setMaximumSize(QtCore.QSize(16777215, 60))
        self.data.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.data.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.data.setObjectName("data")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.data)
        self.horizontalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.data_left = QtWidgets.QFrame(parent=self.data)
        self.data_left.setMaximumSize(QtCore.QSize(80, 16777215))
        self.data_left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.data_left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.data_left.setObjectName("data_left")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.data_left)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.img_vid = QtWidgets.QLabel(parent=self.data_left)
        self.img_vid.setStyleSheet("#img_vid {\n"
"    background-color: #e5e5e5;\n"
"}")
        self.img_vid.setObjectName("img_vid")
        self.horizontalLayout_6.addWidget(self.img_vid)
        self.horizontalLayout_5.addWidget(self.data_left)
        self.data_right = QtWidgets.QFrame(parent=self.data)
        self.data_right.setMaximumSize(QtCore.QSize(120, 16777215))
        self.data_right.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.data_right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.data_right.setObjectName("data_right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.data_right)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(parent=self.data_right)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_time = QtWidgets.QLabel(parent=self.frame_4)
        self.label_time.setStyleSheet("#label_time {\n"
"    font-size: 10px;\n"
"    font-weight: 600;\n"
"}")
        self.label_time.setScaledContents(False)
        self.label_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.horizontalLayout_7.addWidget(self.label_time)
        self.label_date = QtWidgets.QLabel(parent=self.frame_4)
        self.label_date.setStyleSheet("#label_date {\n"
"    font-size: 10px;\n"
"    font-weight: 600;\n"
"}")
        self.label_date.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_date.setObjectName("label_date")
        self.horizontalLayout_7.addWidget(self.label_date)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.data_right)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_category = QtWidgets.QLabel(parent=self.frame_5)
        self.label_category.setStyleSheet("#label_category {\n"
"    padding: 0px 8px;\n"
"    font-size: 10px;\n"
"    font-weight: 600;\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"}")
        self.label_category.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_category.setObjectName("label_category")
        self.verticalLayout_8.addWidget(self.label_category, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.horizontalLayout_5.addWidget(self.data_right)
        self.verticalLayout_data.addWidget(self.data)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_data.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.verticalLayout_data)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.frame_list)
        self.horizontalLayout.addWidget(self.frame_left)
        self.frame_mid = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_mid.setStyleSheet("")
        self.frame_mid.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_mid.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_mid.setObjectName("frame_mid")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_mid)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_media = QtWidgets.QFrame(parent=self.frame_mid)
        self.frame_media.setMinimumSize(QtCore.QSize(0, 500))
        self.frame_media.setStyleSheet("#frame_media {\n"
"    background-color: #f9f9f9;\n"
"    border-radius: 4px;\n"
"}")
        self.frame_media.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_media.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_media.setObjectName("frame_media")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_media)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_vid = QtWidgets.QFrame(parent=self.frame_media)
        self.frame_vid.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_vid.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_vid.setObjectName("frame_vid")
        self.verticalLayout_9.addWidget(self.frame_vid)
        self.frame_player = QtWidgets.QFrame(parent=self.frame_media)
        self.frame_player.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_player.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_player.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_player.setObjectName("frame_player")
        self.verticalLayout_9.addWidget(self.frame_player)
        self.verticalLayout_6.addWidget(self.frame_media)
        self.frame_result = QtWidgets.QFrame(parent=self.frame_mid)
        self.frame_result.setStyleSheet("#frame_result {\n"
"    background-color: #f9f9f9;\n"
"    border-radius: 4px;\n"
"}")
        self.frame_result.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_result.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_result.setObjectName("frame_result")
        self.verticalLayout_6.addWidget(self.frame_result)
        self.horizontalLayout.addWidget(self.frame_mid)
        self.frame_right = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_right.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_right.setStyleSheet("")
        self.frame_right.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_legends = QtWidgets.QFrame(parent=self.frame_right)
        self.frame_legends.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_legends.setStyleSheet("#frame_legends {\n"
"    background-color: #f9f9f9;\n"
"    border-radius: 4px;\n"
"}")
        self.frame_legends.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_legends.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_legends.setObjectName("frame_legends")
        self.verticalLayout_10.addWidget(self.frame_legends)
        self.frame_maps = QtWidgets.QFrame(parent=self.frame_right)
        self.frame_maps.setStyleSheet("#frame_maps {\n"
"    background-color: #f9f9f9;\n"
"    border-radius: 4px;\n"
"}")
        self.frame_maps.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_maps.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_maps.setObjectName("frame_maps")
        
        self.layout = QtWidgets.QVBoxLayout()
        self.frame_maps.setLayout(self.layout)

        coordinate = (37.8199286, -122.4782551)
        m = folium.Map(
            tiles='Stamen Terrain',
            zoom_start=13,
            location=coordinate
        )
        folium.Marker(location=coordinate).add_to(m)

        # save map data to data object
        data = io.BytesIO()
        m.save(data, close_file=False)

        webView = QWebEngineView()
        webView.setHtml(data.getvalue().decode())
        self.layout.addWidget(webView)
        
        self.verticalLayout_10.addWidget(self.frame_maps)
        self.horizontalLayout.addWidget(self.frame_right)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textbox_data.setPlaceholderText(_translate("MainWindow", "Choose Data (.txt)"))
        self.textbox_vid.setPlaceholderText(_translate("MainWindow", "Choose Video (.mp4, etc)"))
        self.btn_submit.setText(_translate("MainWindow", "Submit"))
        self.label_time.setText(_translate("MainWindow", "10:17:53"))
        self.label_date.setText(_translate("MainWindow", "2023-04-09"))
        self.label_category.setText(_translate("MainWindow", "Near Crash"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
