# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimedia import QMediaContent, QMediaPlayer
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtWidgets import (QApplication, QFileDialog, QHBoxLayout, QLabel, 
        QPushButton, QSizePolicy, QSlider, QStyle, QVBoxLayout, QWidget, QStatusBar, QMainWindow)
from PyQt5.QtCore import QUrl



class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()
        
    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(parent=self)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"    background-color: #BDBBBE;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_left = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_left.setMaximumSize(QtCore.QSize(240, 16777215))
        self.frame_left.setStyleSheet("#frame_left {\n"
"    background-color: #f9f9f9;\n"
"    border-radius: 4px;\n"
"}")
        self.frame_left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_data = QtWidgets.QFrame(parent=self.frame_left)
        self.frame_data.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_data.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_data.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_data.setObjectName("frame_data")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_data)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_data_1 = QtWidgets.QFrame(parent=self.frame_data)
        self.frame_data_1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_data_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_data_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_data_1.setObjectName("frame_data_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_data_1)
        self.horizontalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textbox_data = QtWidgets.QPlainTextEdit(parent=self.frame_data_1)
        self.textbox_data.setStyleSheet("#textbox_data {\n"
"    padding: 2px 6px;\n"
"    border-radius: 4px;\n"
"    background: transparent;\n"
"    font-size: 12px;\n"
"    border: 1px solid #BDBBBE;\n"
"}\n"
"")
        self.textbox_data.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textbox_data.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textbox_data.setObjectName("textbox_data")
        self.horizontalLayout_2.addWidget(self.textbox_data)
        self.btn_data = QtWidgets.QPushButton(parent=self.frame_data_1)
        self.btn_data.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_data.setStyleSheet("#btn_data {\n"
"    border-radius:4px;\n"
"    border: 0.5px solid #BDBBBE;\n"
"}\n"
"\n"
"#btn_data:hover{\n"
"    background-color: #D7D5D8;\n"
"}")
        self.btn_data.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/folder_open.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_data.setIcon(icon)
        self.btn_data.setIconSize(QtCore.QSize(24, 24))
        self.btn_data.setObjectName("btn_data")
        
        self.horizontalLayout_2.addWidget(self.btn_data)
        self.verticalLayout_2.addWidget(self.frame_data_1)
        self.frame_data_2 = QtWidgets.QFrame(parent=self.frame_data)
        self.frame_data_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_data_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_data_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_data_2.setObjectName("frame_data_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_data_2)
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textbox_vid = QtWidgets.QPlainTextEdit(parent=self.frame_data_2)
        self.textbox_vid.setStyleSheet("#textbox_vid {\n"
"    padding: 2px 6px;\n"
"    border-radius: 4px;\n"
"    background: transparent;\n"
"    font-size: 12px;\n"
"    border: 1px solid #BDBBBE;\n"
"}\n"
"")
        self.textbox_vid.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textbox_vid.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textbox_vid.setObjectName("textbox_vid")
        self.horizontalLayout_3.addWidget(self.textbox_vid)
        self.btn_vid = QtWidgets.QPushButton(parent=self.frame_data_2)
        self.btn_vid.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_vid.setStyleSheet("#btn_vid {\n"
"    border-radius:4px;\n"
"    border: 0.5px solid #BDBBBE;\n"
"}\n"
"\n"
"#btn_vid:hover{\n"
"    background-color: #D7D5D8;\n"
"}")
        self.btn_vid.setText("")
        self.btn_vid.setIcon(icon)
        self.btn_vid.setIconSize(QtCore.QSize(24, 24))
        self.btn_vid.setObjectName("btn_vid")
        self.btn_vid.clicked.connect(self.open_vid)
        
        self.horizontalLayout_3.addWidget(self.btn_vid)
        self.verticalLayout_2.addWidget(self.frame_data_2)
        self.frame_data_3 = QtWidgets.QFrame(parent=self.frame_data)
        self.frame_data_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_data_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_data_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_data_3.setObjectName("frame_data_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_data_3)
        self.horizontalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_submit = QtWidgets.QPushButton(parent=self.frame_data_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_submit.sizePolicy().hasHeightForWidth())
        self.btn_submit.setSizePolicy(sizePolicy)
        self.btn_submit.setStyleSheet("#btn_submit {\n"
"    padding: 6px 16px;\n"
"    border-radius: 4px;\n"
"    font-size: 12px;\n"
"    background-color: #6A676E;\n"
"    color: #f9f9f9;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#btn_submit:hover {\n"
"    background-color: #514E55;\n"
"}")
        self.btn_submit.setDefault(False)
        self.btn_submit.setFlat(False)
        self.btn_submit.setObjectName("btn_submit")
        self.horizontalLayout_4.addWidget(self.btn_submit)
        self.verticalLayout_2.addWidget(self.frame_data_3)
        self.verticalLayout.addWidget(self.frame_data)
        self.frame_list = QtWidgets.QFrame(parent=self.frame_left)
        self.frame_list.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_list.setStyleSheet("#frame_list {\n"
"    border-top: 2px solid #BDBBBE;\n"
"}")
        self.frame_list.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_list.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_list.setObjectName("frame_list")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_list)
        self.verticalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_list)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("#scrollArea {\n"
"    border: 0px;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 212, 547))
        self.scrollAreaWidgetContents.setStyleSheet("#scrollAreaWidgetContents {\n"
"    background-color: #f9f9f9;\n"
"    border: 0px;\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_data = QtWidgets.QVBoxLayout()
        self.verticalLayout_data.setObjectName("verticalLayout_data")
        self.data = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.data.setMinimumSize(QtCore.QSize(0, 60))
        self.data.setMaximumSize(QtCore.QSize(16777215, 60))
        self.data.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.data.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.data.setObjectName("data")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.data)
        self.horizontalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.data_left = QtWidgets.QFrame(parent=self.data)
        self.data_left.setMaximumSize(QtCore.QSize(80, 16777215))
        self.data_left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.data_left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.data_left.setObjectName("data_left")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.data_left)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.img_vid = QtWidgets.QLabel(parent=self.data_left)
        self.img_vid.setStyleSheet("#img_vid {\n"
"    background-color: #e5e5e5;\n"
"}")
        self.img_vid.setObjectName("img_vid")
        self.horizontalLayout_6.addWidget(self.img_vid)
        self.horizontalLayout_5.addWidget(self.data_left)
        self.data_right = QtWidgets.QFrame(parent=self.data)
        self.data_right.setMaximumSize(QtCore.QSize(120, 16777215))
        self.data_right.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.data_right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.data_right.setObjectName("data_right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.data_right)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(parent=self.data_right)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_time = QtWidgets.QLabel(parent=self.frame_4)
        self.label_time.setStyleSheet("#label_time {\n"
"    font-size: 10px;\n"
"    font-weight: 600;\n"
"}")
        self.label_time.setScaledContents(False)
        self.label_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.horizontalLayout_7.addWidget(self.label_time)
        self.label_date = QtWidgets.QLabel(parent=self.frame_4)
        self.label_date.setStyleSheet("#label_date {\n"
"    font-size: 10px;\n"
"    font-weight: 600;\n"
"}")
        self.label_date.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_date.setObjectName("label_date")
        self.horizontalLayout_7.addWidget(self.label_date)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.data_right)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_category = QtWidgets.QLabel(parent=self.frame_5)
        self.label_category.setStyleSheet("#label_category {\n"
"    padding: 0px 8px;\n"
"    font-size: 10px;\n"
"    font-weight: 600;\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"}")
        self.label_category.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_category.setObjectName("label_category")
        self.verticalLayout_8.addWidget(self.label_category, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.horizontalLayout_5.addWidget(self.data_right)
        self.verticalLayout_data.addWidget(self.data)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_data.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.verticalLayout_data)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.frame_list)
        self.horizontalLayout.addWidget(self.frame_left)
        self.frame_mid = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_mid.setStyleSheet("")
        self.frame_mid.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_mid.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_mid.setObjectName("frame_mid")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_mid)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_media = QtWidgets.QFrame(parent=self.frame_mid)
        self.frame_media.setMinimumSize(QtCore.QSize(0, 500))
        self.frame_media.setStyleSheet("#frame_media {\n"
"    background-color: #f9f9f9;\n"
"    border-radius: 4px;\n"
"}")
        self.frame_media.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_media.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_media.setObjectName("frame_media")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_media)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_vid = QtWidgets.QFrame(parent=self.frame_media)
        self.frame_vid.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_vid.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_vid.setObjectName("frame_vid")
        self.verticalLayout_9.addWidget(self.frame_vid)
        
        self.mediaPlayer = QMediaPlayer(None, QMediaPlayer.VideoSurface)

        btnSize = QtCore.QSize(16, 16)
        videoWidget = QVideoWidget()

        openButton = QPushButton("Open Video")
        openButton.setToolTip("Open Video File")
        openButton.setStatusTip("Open Video File")
        openButton.setFixedHeight(24)
        openButton.setIconSize(btnSize)
        openButton.clicked.connect(self.open_vid)

        self.playButton = QPushButton()
        self.playButton.setEnabled(False)
        self.playButton.setFixedHeight(24)
        self.playButton.setIconSize(btnSize)
        self.playButton.setIcon(self.style().standardIcon(QStyle.SP_MediaPlay))
        self.playButton.clicked.connect(self.play)

        layout = QVBoxLayout()
        layout.addWidget(videoWidget)

        self.frame_vid.setLayout(layout)
                
        self.mediaPlayer.setVideoOutput(videoWidget)
        self.mediaPlayer.stateChanged.connect(self.mediaStateChanged)
        self.mediaPlayer.positionChanged.connect(self.positionChanged)
        self.mediaPlayer.durationChanged.connect(self.durationChanged)
        
        self.frame_player = QtWidgets.QFrame(parent=self.frame_media)
        self.frame_player.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_player.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_player.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_player.setObjectName("frame_player")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_player)
        self.horizontalLayout_10.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_10.setSpacing(9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_play = QtWidgets.QPushButton(parent=self.frame_player)
        self.btn_play.setEnabled(False)
        self.btn_play.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_play.setStyleSheet("")
        self.btn_play.setText("")

        self.btn_play.setIcon(self.frame_player.style().standardIcon(QtWidgets.QStyle.StandardPixmap.SP_MediaPlay))
        self.btn_play.setIconSize(QtCore.QSize(24, 24))
        self.btn_play.setObjectName("btn_play")
        self.btn_play.clicked.connect(self.play)
        
        self.horizontalLayout_10.addWidget(self.btn_play)
        self.horizontalSlider = QtWidgets.QSlider(parent=self.frame_player)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setRange(0, 0)
        self.horizontalSlider.sliderMoved.connect(self.setPosition)
        
        self.horizontalLayout_10.addWidget(self.horizontalSlider)
        self.verticalLayout_9.addWidget(self.frame_player)
        self.verticalLayout_6.addWidget(self.frame_media)
        self.frame_result = QtWidgets.QFrame(parent=self.frame_mid)
        self.frame_result.setStyleSheet("#frame_result {\n"
"    background-color: #f9f9f9;\n"
"    border-radius: 4px;\n"
"}")
        self.frame_result.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_result.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_result.setObjectName("frame_result")
        self.verticalLayout_6.addWidget(self.frame_result)
        self.horizontalLayout.addWidget(self.frame_mid)
        self.frame_right = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_right.setMaximumSize(QtCore.QSize(320, 16777215))
        self.frame_right.setStyleSheet("")
        self.frame_right.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_legends = QtWidgets.QFrame(parent=self.frame_right)
        self.frame_legends.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frame_legends.setStyleSheet("#frame_legends {\n"
"    background-color: #f9f9f9;\n"
"    border-radius: 4px;\n"
"}")
        self.frame_legends.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_legends.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_legends.setObjectName("frame_legends")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_legends)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_speed = QtWidgets.QFrame(parent=self.frame_legends)
        self.frame_speed.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_speed.setStyleSheet("")
        self.frame_speed.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_speed.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_speed.setObjectName("frame_speed")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_speed)
        self.horizontalLayout_8.setContentsMargins(4, -1, 4, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_speed = QtWidgets.QLabel(parent=self.frame_speed)
        self.label_speed.setObjectName("label_speed")
        self.horizontalLayout_8.addWidget(self.label_speed)
        self.label_speed_2 = QtWidgets.QLabel(parent=self.frame_speed)
        self.label_speed_2.setStyleSheet("#label_speed_2 {\n"
"    font-weight: 600;\n"
"}")
        self.label_speed_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_speed_2.setObjectName("label_speed_2")
        self.horizontalLayout_8.addWidget(self.label_speed_2)
        self.verticalLayout_11.addWidget(self.frame_speed)
        self.frame_coordinates = QtWidgets.QFrame(parent=self.frame_legends)
        self.frame_coordinates.setStyleSheet("#frame_coordinates {\n"
"    border-top: 2px solid #BDBBBE;\n"
"}")
        self.frame_coordinates.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_coordinates.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_coordinates.setObjectName("frame_coordinates")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_coordinates)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_coordinates_left = QtWidgets.QFrame(parent=self.frame_coordinates)
        self.frame_coordinates_left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_coordinates_left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_coordinates_left.setObjectName("frame_coordinates_left")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_coordinates_left)
        self.verticalLayout_12.setContentsMargins(4, -1, 4, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_coordinates = QtWidgets.QLabel(parent=self.frame_coordinates_left)
        self.label_coordinates.setObjectName("label_coordinates")
        self.verticalLayout_12.addWidget(self.label_coordinates)
        self.horizontalLayout_9.addWidget(self.frame_coordinates_left)
        self.frame_coordinates_right = QtWidgets.QFrame(parent=self.frame_coordinates)
        self.frame_coordinates_right.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_coordinates_right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_coordinates_right.setObjectName("frame_coordinates_right")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_coordinates_right)
        self.verticalLayout_13.setContentsMargins(4, -1, 4, -1)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_coord_2 = QtWidgets.QLabel(parent=self.frame_coordinates_right)
        self.label_coord_2.setStyleSheet("#label_coord_2 {\n"
"    font-weight: 600;\n"
"}")
        self.label_coord_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_coord_2.setObjectName("label_coord_2")
        self.verticalLayout_13.addWidget(self.label_coord_2)
        self.label_coord_1 = QtWidgets.QLabel(parent=self.frame_coordinates_right)
        self.label_coord_1.setStyleSheet("#label_coord_1 {\n"
"    font-weight: 600;\n"
"}")
        self.label_coord_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_coord_1.setObjectName("label_coord_1")
        self.verticalLayout_13.addWidget(self.label_coord_1)
        self.horizontalLayout_9.addWidget(self.frame_coordinates_right)
        self.verticalLayout_11.addWidget(self.frame_coordinates)
        self.verticalLayout_10.addWidget(self.frame_legends)
        self.frame_maps = QtWidgets.QFrame(parent=self.frame_right)
        self.frame_maps.setStyleSheet("#frame_maps {\n"
"    background-color: #f9f9f9;\n"
"    border-radius: 4px;\n"
"}")
        self.frame_maps.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_maps.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_maps.setObjectName("frame_maps")
        self.verticalLayout_10.addWidget(self.frame_maps)
        self.horizontalLayout.addWidget(self.frame_right)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        
    def open_vid(self):
        fileName, _ = QFileDialog.getOpenFileName(self, "Open File",
                                                  ".", "Video Files (*.mp4 *.flv *.ts *.mts *.avi *.m4v)")

        if fileName != '':
            self.mediaPlayer.setMedia(QMediaContent(QUrl.fromLocalFile(fileName)))
            self.btn_play.setEnabled(True)
        
    def setPosition(self, position):
        self.mediaPlayer.setPosition(position)
    
    def play(self):
        if self.mediaPlayer.state() == QMediaPlayer.PlayingState:
            self.mediaPlayer.pause()
        else:
            self.mediaPlayer.play()
    
    def positionChanged(self, position):
        self.horizontalSlider.setValue(position)

    def durationChanged(self, duration):
        self.horizontalSlider.setRange(0, duration)
    
    def mediaStateChanged(self, state):
        if self.mediaPlayer.state() == QMediaPlayer.PlayingState:
            self.btn_play.setIcon(
                self.style().standardIcon(QtWidgets.QStyle.SP_MediaPause))
        else:
            self.btn_play.setIcon(
                self.style().standardIcon(QtWidgets.QStyle.SP_MediaPlay))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textbox_data.setPlaceholderText(_translate("MainWindow", "Choose Data (.txt)"))
        self.textbox_vid.setPlaceholderText(_translate("MainWindow", "Choose Video (.mp4, etc)"))
        self.btn_submit.setText(_translate("MainWindow", "Submit"))
        self.label_time.setText(_translate("MainWindow", "10:17:53"))
        self.label_date.setText(_translate("MainWindow", "2023-04-09"))
        self.label_category.setText(_translate("MainWindow", "Near Crash"))
        self.label_speed.setText(_translate("MainWindow", "Driving Speed"))
        self.label_speed_2.setText(_translate("MainWindow", "004 km/h"))
        self.label_coordinates.setText(_translate("MainWindow", "Coordinates"))
        self.label_coord_2.setText(_translate("MainWindow", "lat: 40.6892"))
        self.label_coord_1.setText(_translate("MainWindow", "long: -74.0445"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
